### ISSUE TITLE
Are we not having placeholders in text/password fields?

### ISSUE THREAD

**Issue by peggylind** [DataAnalyticsinStudentHands/VolunteerManagementApp#10]
Just opened the App on my phone (Sony Xperia Compact z1) the first time and don't see any placeholders. 

![screenshot_2015-02-12-09-25-20](https://cloud.githubusercontent.com/assets/6371988/6170330/5d385d4e-b299-11e4-8fa7-7b37c2dcf859.png)

**Comment by nqv1994** [comment]
We have, but the color is off. 
I can fix it this afternoon

**Comment by nqv1994** [comment]
Pushed to Front-Vu

**Comment by CarlSteven** [comment]
Merged and hydrate updated.
